/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Count prime numbers up to `limit` in parallel.
 *
 * # Errors
 * Returns an error when `limit` exceeds the configured safeguard.
 */
export declare function countPrimes(limit: number): number
/**
 * Multiply two N x N matrices represented as flattened row-major arrays.
 *
 * # Errors
 * Returns an error when size or vector lengths are invalid.
 */
export declare function matrixMultiplyParallel(left: Array<number>, right: Array<number>, size: number): Array<number>
/**
 * Compute dot product for two vectors in parallel.
 *
 * # Errors
 * Returns an error when vectors are empty, oversized, or shape-mismatched.
 */
export declare function dotProductParallel(left: Array<number>, right: Array<number>): number
