/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PrimeTimedResult {
  result: number
  computeMs: number
}
export interface DotTimedResult {
  result: number
  computeMs: number
}
export interface MatrixSummaryTimedResult {
  length: number
  first: number
  checksum: number
  computeMs: number
}
/**
 * Count prime numbers up to `limit` in parallel.
 *
 * # Errors
 * Returns an error when `limit` exceeds the configured safeguard.
 */
export declare function countPrimes(limit: number): number
/**
 * Count prime numbers and return native compute timing in milliseconds.
 *
 * # Errors
 * Returns an error when `limit` exceeds the configured safeguard.
 */
export declare function countPrimesTimed(limit: number): PrimeTimedResult
/**
 * Batch prime counting in one native call and return average native compute timing.
 *
 * # Errors
 * Returns an error when arguments exceed configured safeguards.
 */
export declare function countPrimesBatchTimed(limit: number, iterations: number): PrimeTimedResult
/**
 * Multiply two N x N matrices represented as flattened row-major arrays.
 *
 * # Errors
 * Returns an error when size or vector lengths are invalid.
 */
export declare function matrixMultiplyParallel(left: Float64Array, right: Float64Array, size: number): Array<number>
/**
 * Multiply matrix inputs and return summary with native compute timing.
 *
 * # Errors
 * Returns an error when size or vector lengths are invalid.
 */
export declare function matrixMultiplySummaryTimed(left: Float64Array, right: Float64Array, size: number): MatrixSummaryTimedResult
/**
 * Batch matrix summary computation in one native call and return average native compute timing.
 *
 * # Errors
 * Returns an error when arguments exceed configured safeguards.
 */
export declare function matrixMultiplySummaryBatchTimed(left: Float64Array, right: Float64Array, size: number, iterations: number): MatrixSummaryTimedResult
/**
 * Compute dot product for two vectors in parallel.
 *
 * # Errors
 * Returns an error when vectors are empty, oversized, or shape-mismatched.
 */
export declare function dotProductParallel(left: Float64Array, right: Float64Array): number
/**
 * Compute dot product and return native compute timing in milliseconds.
 *
 * # Errors
 * Returns an error when vectors are empty, oversized, or shape-mismatched.
 */
export declare function dotProductTimed(left: Float64Array, right: Float64Array): DotTimedResult
/**
 * Batch dot product in one native call and return average native compute timing.
 *
 * # Errors
 * Returns an error when arguments exceed configured safeguards.
 */
export declare function dotProductBatchTimed(left: Float64Array, right: Float64Array, iterations: number): DotTimedResult
